<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::truncate();

        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AF', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-af.svg'],
            ['name' => 'Åland Islands', 'code' => 'AX', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ax.svg'],
            ['name' => 'Albania', 'code' => 'AL', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-al.svg'],
            ['name' => 'Algeria', 'code' => 'DZ', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-dz.svg'],
            ['name' => 'American Samoa', 'code' => 'AS', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-as.svg'],
            ['name' => 'Andorra', 'code' => 'AD', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ad.svg'],
            ['name' => 'Angola', 'code' => 'AO', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ao.svg'],
            ['name' => 'Anguilla', 'code' => 'AI', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ai.svg'],
            ['name' => 'Antarctica', 'code' => 'AQ', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-aq.svg'],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ag.svg'],
            ['name' => 'Argentina', 'code' => 'AR', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ar.svg'],
            ['name' => 'Armenia', 'code' => 'AM', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-am.svg'],
            ['name' => 'Aruba', 'code' => 'AW', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-aw.svg'],
            ['name' => 'Australia', 'code' => 'AU', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-au.svg'],
            ['name' => 'Austria', 'code' => 'AT', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-at.svg'],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-az.svg'],
            ['name' => 'Bahamas', 'code' => 'BS', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-bs.svg'],
            ['name' => 'Bahrain', 'code' => 'BH', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-bh.svg'],
            ['name' => 'Bangladesh', 'code' => 'BD', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-bd.svg'],
            ['name' => 'Barbados', 'code' => 'BB', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-bb.svg'],
            ['name' => 'Belarus', 'code' => 'BY', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-by.svg'],
            ['name' => 'Belgium', 'code' => 'BE', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-be.svg'],
            ['name' => 'Belize', 'code' => 'BZ', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-bz.svg'],
            ['name' => 'Benin', 'code' => 'BJ', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-bj.svg'],
            ['name' => 'Bermuda', 'code' => 'BM', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-bm.svg'],
            ['name' => 'Bhutan', 'code' => 'BT', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-bt.svg'],
            ['name' => 'Bolivia, Plurinational State of', 'code' => 'BO', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-bo.svg'],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BQ', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-bq.svg'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ba.svg'],
            ['name' => 'Botswana', 'code' => 'BW', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-bw.svg'],
            ['name' => 'Bouvet Island', 'code' => 'BV', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-bv.svg'],
            ['name' => 'Brazil', 'code' => 'BR', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-br.svg'],
            ['name' => 'British Indian Ocean Territory', 'code' => 'IO', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-io.svg'],
            ['name' => 'Brunei Darussalam', 'code' => 'BN', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-bn.svg'],
            ['name' => 'Bulgaria', 'code' => 'BG', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-bg.svg'],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-bf.svg'],
            ['name' => 'Burundi', 'code' => 'BI', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-bi.svg'],
            ['name' => 'Cambodia', 'code' => 'KH', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-kh.svg'],
            ['name' => 'Cameroon', 'code' => 'CM', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-cm.svg'],
            ['name' => 'Canada', 'code' => 'CA', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ca.svg'],
            ['name' => 'Cape Verde', 'code' => 'CV', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-cv.svg'],
            ['name' => 'Cayman Islands', 'code' => 'KY', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ky.svg'],
            ['name' => 'Central African Republic', 'code' => 'CF', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-cf.svg'],
            ['name' => 'Chad', 'code' => 'TD', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-td.svg'],
            ['name' => 'Chile', 'code' => 'CL', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-cl.svg'],
            ['name' => 'China', 'code' => 'CN', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-cn.svg'],
            ['name' => 'Christmas Island', 'code' => 'CX', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-cx.svg'],
            ['name' => 'Cocos (Keeling) Islands', 'code' => 'CC', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-cc.svg'],
            ['name' => 'Colombia', 'code' => 'CO', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-co.svg'],
            ['name' => 'Comoros', 'code' => 'KM', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-km.svg'],
            ['name' => 'Congo', 'code' => 'CG', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-cg.svg'],
            ['name' => 'Congo, the Democratic Republic of the', 'code' => 'CD', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-cd.svg'],
            ['name' => 'Cook Islands', 'code' => 'CK', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ck.svg'],
            ['name' => 'Costa Rica', 'code' => 'CR', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-cr.svg'],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CI', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ci.svg'],
            ['name' => 'Croatia', 'code' => 'HR', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-hr.svg'],
            ['name' => 'Cuba', 'code' => 'CU', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-cu.svg'],
            ['name' => 'Curaçao', 'code' => 'CW', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-cw.svg'],
            ['name' => 'Cyprus', 'code' => 'CY', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-cy.svg'],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-cz.svg'],
            ['name' => 'Denmark', 'code' => 'DK', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-dk.svg'],
            ['name' => 'Djibouti', 'code' => 'DJ', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-dj.svg'],
            ['name' => 'Dominica', 'code' => 'DM', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-dm.svg'],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-do.svg'],
            ['name' => 'Ecuador', 'code' => 'EC', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ec.svg'],
            ['name' => 'Egypt', 'code' => 'EG', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-eg.svg'],
            ['name' => 'El Salvador', 'code' => 'SV', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-sv.svg'],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-gq.svg'],
            ['name' => 'Eritrea', 'code' => 'ER', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-er.svg'],
            ['name' => 'Estonia', 'code' => 'EE', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ee.svg'],
            ['name' => 'Ethiopia', 'code' => 'ET', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-et.svg'],
            ['name' => 'Falkland Islands (Malvinas)', 'code' => 'FK', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-fk.svg'],
            ['name' => 'Faroe Islands', 'code' => 'FO', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-fo.svg'],
            ['name' => 'Fiji', 'code' => 'FJ', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-fj.svg'],
            ['name' => 'Finland', 'code' => 'FI', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-fi.svg'],
            ['name' => 'France', 'code' => 'FR', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-fr.svg'],
            ['name' => 'French Guiana', 'code' => 'GF', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-gf.svg'],
            ['name' => 'French Polynesia', 'code' => 'PF', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-pf.svg'],
            ['name' => 'French Southern Territories', 'code' => 'TF', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-tf.svg'],
            ['name' => 'Gabon', 'code' => 'GA', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ga.svg'],
            ['name' => 'Gambia', 'code' => 'GM', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-gm.svg'],
            ['name' => 'Georgia', 'code' => 'GE', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ge.svg'],
            ['name' => 'Germany', 'code' => 'DE', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-de.svg'],
            ['name' => 'Ghana', 'code' => 'GH', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-gh.svg'],
            ['name' => 'Gibraltar', 'code' => 'GI', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-gi.svg'],
            ['name' => 'Greece', 'code' => 'GR', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-gr.svg'],
            ['name' => 'Greenland', 'code' => 'GL', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-gl.svg'],
            ['name' => 'Grenada', 'code' => 'GD', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-gd.svg'],
            ['name' => 'Guadeloupe', 'code' => 'GP', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-gp.svg'],
            ['name' => 'Guam', 'code' => 'GU', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-gu.svg'],
            ['name' => 'Guatemala', 'code' => 'GT', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-gt.svg'],
            ['name' => 'Guernsey', 'code' => 'GG', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-gg.svg'],
            ['name' => 'Guinea', 'code' => 'GN', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-gn.svg'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-gw.svg'],
            ['name' => 'Guyana', 'code' => 'GY', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-gy.svg'],
            ['name' => 'Haiti', 'code' => 'HT', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ht.svg'],
            ['name' => 'Heard Island and McDonald Mcdonald Islands', 'code' => 'HM', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-hm.svg'],
            ['name' => 'Holy See (Vatican City State)', 'code' => 'VA', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-va.svg'],
            ['name' => 'Honduras', 'code' => 'HN', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-hn.svg'],
            ['name' => 'Hong Kong', 'code' => 'HK', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-hk.svg'],
            ['name' => 'Hungary', 'code' => 'HU', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-hu.svg'],
            ['name' => 'Iceland', 'code' => 'IS', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-is.svg'],
            ['name' => 'India', 'code' => 'IN', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-in.svg'],
            ['name' => 'Indonesia', 'code' => 'ID', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-id.svg'],
            ['name' => 'Iran, Islamic Republic of', 'code' => 'IR', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ir.svg'],
            ['name' => 'Iraq', 'code' => 'IQ', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-iq.svg'],
            ['name' => 'Ireland', 'code' => 'IE', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ie.svg'],
            ['name' => 'Isle of Man', 'code' => 'IM', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-im.svg'],
            ['name' => 'Israel', 'code' => 'IL', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-il.svg'],
            ['name' => 'Italy', 'code' => 'IT', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-it.svg'],
            ['name' => 'Jamaica', 'code' => 'JM', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-jm.svg'],
            ['name' => 'Japan', 'code' => 'JP', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-jp.svg'],
            ['name' => 'Jersey', 'code' => 'JE', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-je.svg'],
            ['name' => 'Jordan', 'code' => 'JO', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-jo.svg'],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-kz.svg'],
            ['name' => 'Kenya', 'code' => 'KE', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ke.svg'],
            ['name' => 'Kiribati', 'code' => 'KI', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ki.svg'],
            ['name' => 'Korea, Democratic People\'s Republic of', 'code' => 'KP', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-kp.svg'],
            ['name' => 'Korea, Republic of', 'code' => 'KR', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-kr.svg'],
            ['name' => 'Kuwait', 'code' => 'KW', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-kw.svg'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-kg.svg'],
            ['name' => 'Lao People\'s Democratic Republic', 'code' => 'LA', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-la.svg'],
            ['name' => 'Latvia', 'code' => 'LV', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-lv.svg'],
            ['name' => 'Lebanon', 'code' => 'LB', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-lb.svg'],
            ['name' => 'Lesotho', 'code' => 'LS', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ls.svg'],
            ['name' => 'Liberia', 'code' => 'LR', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-lr.svg'],
            ['name' => 'Libya', 'code' => 'LY', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ly.svg'],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-li.svg'],
            ['name' => 'Lithuania', 'code' => 'LT', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-lt.svg'],
            ['name' => 'Luxembourg', 'code' => 'LU', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-lu.svg'],
            ['name' => 'Macao', 'code' => 'MO', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-mo.svg'],
            ['name' => 'Macedonia, the Former Yugoslav Republic of', 'code' => 'MK', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-mk.svg'],
            ['name' => 'Madagascar', 'code' => 'MG', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-mg.svg'],
            ['name' => 'Malawi', 'code' => 'MW', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-mw.svg'],
            ['name' => 'Malaysia', 'code' => 'MY', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-my.svg'],
            ['name' => 'Maldives', 'code' => 'MV', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-mv.svg'],
            ['name' => 'Mali', 'code' => 'ML', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ml.svg'],
            ['name' => 'Malta', 'code' => 'MT', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-mt.svg'],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-mh.svg'],
            ['name' => 'Martinique', 'code' => 'MQ', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-mq.svg'],
            ['name' => 'Mauritania', 'code' => 'MR', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-mr.svg'],
            ['name' => 'Mauritius', 'code' => 'MU', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-mu.svg'],
            ['name' => 'Mayotte', 'code' => 'YT', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-yt.svg'],
            ['name' => 'Mexico', 'code' => 'MX', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-mx.svg'],
            ['name' => 'Micronesia, Federated States of', 'code' => 'FM', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-fm.svg'],
            ['name' => 'Moldova, Republic of', 'code' => 'MD', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-md.svg'],
            ['name' => 'Monaco', 'code' => 'MC', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-mc.svg'],
            ['name' => 'Mongolia', 'code' => 'MN', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-mn.svg'],
            ['name' => 'Montenegro', 'code' => 'ME', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-me.svg'],
            ['name' => 'Montserrat', 'code' => 'MS', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ms.svg'],
            ['name' => 'Morocco', 'code' => 'MA', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ma.svg'],
            ['name' => 'Mozambique', 'code' => 'MZ', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-mz.svg'],
            ['name' => 'Myanmar', 'code' => 'MM', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-mm.svg'],
            ['name' => 'Namibia', 'code' => 'NA', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-na.svg'],
            ['name' => 'Nauru', 'code' => 'NR', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-nr.svg'],
            ['name' => 'Nepal', 'code' => 'NP', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-np.svg'],
            ['name' => 'Netherlands', 'code' => 'NL', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-nl.svg'],
            ['name' => 'New Caledonia', 'code' => 'NC', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-nc.svg'],
            ['name' => 'New Zealand', 'code' => 'NZ', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-nz.svg'],
            ['name' => 'Nicaragua', 'code' => 'NI', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ni.svg'],
            ['name' => 'Niger', 'code' => 'NE', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ne.svg'],
            ['name' => 'Nigeria', 'code' => 'NG', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ng.svg'],
            ['name' => 'Niue', 'code' => 'NU', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-nu.svg'],
            ['name' => 'Norfolk Island', 'code' => 'NF', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-nf.svg'],
            ['name' => 'Northern Mariana Islands', 'code' => 'MP', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-mp.svg'],
            ['name' => 'Norway', 'code' => 'NO', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-no.svg'],
            ['name' => 'Oman', 'code' => 'OM', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-om.svg'],
            ['name' => 'Pakistan', 'code' => 'PK', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-pk.svg'],
            ['name' => 'Palau', 'code' => 'PW', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-pw.svg'],
            ['name' => 'Palestine, State of', 'code' => 'PS', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ps.svg'],
            ['name' => 'Panama', 'code' => 'PA', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-pa.svg'],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-pg.svg'],
            ['name' => 'Paraguay', 'code' => 'PY', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-py.svg'],
            ['name' => 'Peru', 'code' => 'PE', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-pe.svg'],
            ['name' => 'Philippines', 'code' => 'PH', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ph.svg'],
            ['name' => 'Pitcairn', 'code' => 'PN', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-pn.svg'],
            ['name' => 'Poland', 'code' => 'PL', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-pl.svg'],
            ['name' => 'Portugal', 'code' => 'PT', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-pt.svg'],
            ['name' => 'Puerto Rico', 'code' => 'PR', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-pr.svg'],
            ['name' => 'Qatar', 'code' => 'QA', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-qa.svg'],
            ['name' => 'Réunion', 'code' => 'RE', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-re.svg'],
            ['name' => 'Romania', 'code' => 'RO', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ro.svg'],
            ['name' => 'Russian Federation', 'code' => 'RU', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ru.svg'],
            ['name' => 'Rwanda', 'code' => 'RW', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-rw.svg'],
            ['name' => 'Saint Barthélemy', 'code' => 'BL', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-bl.svg'],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'SH', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-sh.svg'],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-kn.svg'],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-lc.svg'],
            ['name' => 'Saint Martin (French part)', 'code' => 'MF', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-mf.svg'],
            ['name' => 'Saint Pierre and Miquelon', 'code' => 'PM', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-pm.svg'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-vc.svg'],
            ['name' => 'Samoa', 'code' => 'WS', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ws.svg'],
            ['name' => 'San Marino', 'code' => 'SM', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-sm.svg'],
            ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-st.svg'],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-sa.svg'],
            ['name' => 'Senegal', 'code' => 'SN', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-sn.svg'],
            ['name' => 'Serbia', 'code' => 'RS', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-rs.svg'],
            ['name' => 'Seychelles', 'code' => 'SC', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-sc.svg'],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-sl.svg'],
            ['name' => 'Singapore', 'code' => 'SG', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-sg.svg'],
            ['name' => 'Sint Maarten (Dutch part)', 'code' => 'SX', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-sx.svg'],
            ['name' => 'Slovakia', 'code' => 'SK', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-sk.svg'],
            ['name' => 'Slovenia', 'code' => 'SI', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-si.svg'],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-sb.svg'],
            ['name' => 'Somalia', 'code' => 'SO', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-so.svg'],
            ['name' => 'South Africa', 'code' => 'ZA', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-za.svg'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-gs.svg'],
            ['name' => 'South Sudan', 'code' => 'SS', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ss.svg'],
            ['name' => 'Spain', 'code' => 'ES', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-es.svg'],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-lk.svg'],
            ['name' => 'Sudan', 'code' => 'SD', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-sd.svg'],
            ['name' => 'Suriname', 'code' => 'SR', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-sr.svg'],
            ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-sj.svg'],
            ['name' => 'Swaziland', 'code' => 'SZ', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-sz.svg'],
            ['name' => 'Sweden', 'code' => 'SE', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-se.svg'],
            ['name' => 'Switzerland', 'code' => 'CH', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ch.svg'],
            ['name' => 'Syrian Arab Republic', 'code' => 'SY', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-sy.svg'],
            ['name' => 'Taiwan', 'code' => 'TW', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-tw.svg'],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-tj.svg'],
            ['name' => 'Tanzania, United Republic of', 'code' => 'TZ', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-tz.svg'],
            ['name' => 'Thailand', 'code' => 'TH', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-th.svg'],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-tl.svg'],
            ['name' => 'Togo', 'code' => 'TG', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-tg.svg'],
            ['name' => 'Tokelau', 'code' => 'TK', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-tk.svg'],
            ['name' => 'Tonga', 'code' => 'TO', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-to.svg'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-tt.svg'],
            ['name' => 'Tunisia', 'code' => 'TN', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-tn.svg'],
            ['name' => 'Turkey', 'code' => 'TR', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-tr.svg'],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-tm.svg'],
            ['name' => 'Turks and Caicos Islands', 'code' => 'TC', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-tc.svg'],
            ['name' => 'Tuvalu', 'code' => 'TV', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-tv.svg'],
            ['name' => 'Uganda', 'code' => 'UG', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ug.svg'],
            ['name' => 'Ukraine', 'code' => 'UA', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ua.svg'],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ae.svg'],
            ['name' => 'United Kingdom', 'code' => 'GB', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-gb.svg'],
            ['name' => 'United States', 'code' => 'US', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-us.svg'],
            ['name' => 'United States Minor Outlying Islands', 'code' => 'UM', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-um.svg'],
            ['name' => 'Uruguay', 'code' => 'UY', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-uy.svg'],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-uz.svg'],
            ['name' => 'Vanuatu', 'code' => 'VU', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-vu.svg'],
            ['name' => 'Venezuela, Bolivarian Republic of', 'code' => 'VE', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ve.svg'],
            ['name' => 'Viet Nam', 'code' => 'VN', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-vn.svg'],
            ['name' => 'Virgin Islands, British', 'code' => 'VG', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-vg.svg'],
            ['name' => 'Virgin Islands, U.S.', 'code' => 'VI', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-vi.svg'],
            ['name' => 'Wallis and Futuna', 'code' => 'WF', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-wf.svg'],
            ['name' => 'Western Sahara', 'code' => 'EH', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-eh.svg'],
            ['name' => 'Yemen', 'code' => 'YE', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-ye.svg'],
            ['name' => 'Zambia', 'code' => 'ZM', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-zm.svg'],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'flag' => '/vendor/outhebox/blade-flags/resources/svg/country-zw.svg'],
        ];

        foreach ($countries as $key => $value) {
            Country::create($value);
        }
    }
}
