<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MedicalCenter;
use App\Models\Specialty;
use Carbon\Carbon;
use Illuminate\Support\Str;

class MedicalCenterSeeder extends Seeder
{
    public function run()
    {
        // مسح البيانات القديمة إذا وجدت
        MedicalCenter::query()->delete();

        // إنشاء تخصصات إذا لم تكن موجودة
        $specialties = Specialty::all();
        if ($specialties->isEmpty()) {
            $specialties = Specialty::factory()->count(15)->create();
        }

        $medicalCenters = [
            // مستشفيات في دبي
            [
                'name' => 'مستشفى دبي',
                'type' => 'hospital',
                'email' => 'info@dubaihospital.ae',
                'phone' => '+97142212000',
                'website' => 'https://www.dha.gov.ae',
                'address' => 'شارع الوصل، دبي',
                'city' => 'دبي',
                'state' => 'إمارة دبي',
                'country' => 'الإمارات',
                'postal_code' => '00000',
                'latitude' => 25.2407,  // خط العرض لدبي
                'longitude' => 55.2950, // خط الطول لدبي
                'description' => 'أحد أكبر المستشفيات الحكومية في دبي، يقدم خدمات طبية متكاملة ومتطورة.',
                'services' => json_encode(['استشارات طبية', 'فحوصات مخبرية', 'أشعة وتصوير', 'طوارئ 24/7', 'عمليات جراحية', 'رعاية أسنان', 'عيون', 'أطفال', 'نساء وتوليد']),
                'facilities' => json_encode(['مواقف سيارات مجانية', 'إنترنت لاسلكي', 'تكييف مركزي', 'مصلى', 'كافيتيريا', 'صيدلية', 'غرف انتظار مريحة', 'مدخل لذوي الاحتياجات']),
                'insurance_providers' => json_encode(['أمان', 'أكسا الخليج', 'أسيج', 'ألفا', 'بيانات']),
                'specialties' => json_encode($specialties->pluck('id')->toArray()),
                'working_hours' => json_encode([
                    'sunday' => ['open' => '08:00', 'close' => '22:00', 'closed' => false],
                    'monday' => ['open' => '08:00', 'close' => '22:00', 'closed' => false],
                    'tuesday' => ['open' => '08:00', 'close' => '22:00', 'closed' => false],
                    'wednesday' => ['open' => '08:00', 'close' => '22:00', 'closed' => false],
                    'thursday' => ['open' => '08:00', 'close' => '22:00', 'closed' => false],
                    'friday' => ['open' => '14:00', 'close' => '22:00', 'closed' => false],
                    'saturday' => ['open' => '08:00', 'close' => '22:00', 'closed' => false],
                ]),
                'doctor_count' => 200,
                'average_rating' => 4.7,
                'rating_count' => 1500,
                'is_verified' => true,
                'is_featured' => true,
                'status' => 'active',
            ],
            [
                'name' => 'مستشفى راشد',
                'type' => 'hospital',
                'email' => 'info@rashidhospital.ae',
                'phone' => '+97143213000',
                'website' => 'https://www.dha.gov.ae',
                'address' => 'أم حرير، دبي',
                'city' => 'دبي',
                'state' => 'إمارة دبي',
                'country' => 'الإمارات',
                'postal_code' => '00000',
                'latitude' => 25.2275,
                'longitude' => 55.3378,
                'description' => 'مستشفى متخصص في طب الطوارئ والرعاية الحرجة، يعد أحد أهم مراكز الطوارئ في دبي.',
                'services' => json_encode(['طوارئ 24/7', 'رعاية حرجة', 'عمليات جراحية', 'عناية مركزة', 'أشعة متطورة', 'مختبرات']),
                'facilities' => json_encode(['مواقف سيارات', 'إنترنت لاسلكي', 'تكييف', 'مصلى', 'صيدلية', 'مطعم', 'بنك', 'متجر هدايا']),
                'insurance_providers' => json_encode(['أمان', 'أكسا الخليج', 'نورا', 'بيانات', 'تكافل']),
                'specialties' => json_encode($specialties->whereIn('name_en', ['Emergency Medicine', 'Surgery', 'Internal Medicine'])->pluck('id')->toArray()),
                'working_hours' => json_encode([
                    'sunday' => ['open' => '00:00', 'close' => '23:59', 'closed' => false],
                    'monday' => ['open' => '00:00', 'close' => '23:59', 'closed' => false],
                    'tuesday' => ['open' => '00:00', 'close' => '23:59', 'closed' => false],
                    'wednesday' => ['open' => '00:00', 'close' => '23:59', 'closed' => false],
                    'thursday' => ['open' => '00:00', 'close' => '23:59', 'closed' => false],
                    'friday' => ['open' => '00:00', 'close' => '23:59', 'closed' => false],
                    'saturday' => ['open' => '00:00', 'close' => '23:59', 'closed' => false],
                ]),
                'doctor_count' => 180,
                'average_rating' => 4.6,
                'rating_count' => 1200,
                'is_verified' => true,
                'is_featured' => true,
                'status' => 'active',
            ],

            // مستشفيات في الشارقة
            [
                'name' => 'مستشفى القاسمي',
                'type' => 'hospital',
                'email' => 'info@alqassimihospital.ae',
                'phone' => '+97165050505',
                'website' => 'https://www.alqassimihospital.ae',
                'address' => 'الشارقة',
                'city' => 'الشارقة',
                'state' => 'إمارة الشارقة',
                'country' => 'الإمارات',
                'postal_code' => '00000',
                'latitude' => 25.3573,
                'longitude' => 55.3919,
                'description' => 'مستشفى حديث يقدم خدمات طبية متكاملة في إمارة الشارقة.',
                'services' => json_encode(['استشارات طبية', 'فحوصات مخبرية', 'أشعة', 'طوارئ', 'عمليات', 'أسنان']),
                'facilities' => json_encode(['مواقف سيارات', 'إنترنت لاسلكي', 'تكييف', 'مصلى', 'صيدلية']),
                'insurance_providers' => json_encode(['أكسا الخليج', 'نورا', 'بيانات']),
                'specialties' => json_encode($specialties->take(10)->pluck('id')->toArray()),
                'working_hours' => json_encode([
                    'sunday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                    'monday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                    'tuesday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                    'wednesday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                    'thursday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                    'friday' => ['open' => '14:00', 'close' => '20:00', 'closed' => false],
                    'saturday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                ]),
                'doctor_count' => 85,
                'average_rating' => 4.4,
                'rating_count' => 650,
                'is_verified' => true,
                'is_featured' => false,
                'status' => 'active',
            ],

            // مستشفيات في أبو ظبي
            [
                'name' => 'مستشفى الشيخ خليفة',
                'type' => 'hospital',
                'email' => 'info@skmc.ae',
                'phone' => '+97125050000',
                'website' => 'https://www.skmc.ae',
                'address' => 'أبو ظبي',
                'city' => 'أبو ظبي',
                'state' => 'إمارة أبو ظبي',
                'country' => 'الإمارات',
                'postal_code' => '00000',
                'latitude' => 24.4829,
                'longitude' => 54.3583,
                'description' => 'مستشفى تابع للخدمات الطبية للقوات المسلحة، يقدم خدمات طبية متطورة.',
                'services' => json_encode(['استشارات متخصصة', 'عمليات دقيقة', 'رعاية قلبية', 'أورام', 'أشعة متطورة']),
                'facilities' => json_encode(['مواقف سيارات', 'إنترنت لاسلكي', 'تكييف', 'مصلى', 'مطاعم', 'مقاهي', 'صيدلية']),
                'insurance_providers' => json_encode(['أمان', 'أكسا الخليج', 'بيانات', 'تكافل']),
                'specialties' => json_encode($specialties->pluck('id')->toArray()),
                'working_hours' => json_encode([
                    'sunday' => ['open' => '07:00', 'close' => '23:00', 'closed' => false],
                    'monday' => ['open' => '07:00', 'close' => '23:00', 'closed' => false],
                    'tuesday' => ['open' => '07:00', 'close' => '23:00', 'closed' => false],
                    'wednesday' => ['open' => '07:00', 'close' => '23:00', 'closed' => false],
                    'thursday' => ['open' => '07:00', 'close' => '23:00', 'closed' => false],
                    'friday' => ['open' => '14:00', 'close' => '23:00', 'closed' => false],
                    'saturday' => ['open' => '07:00', 'close' => '23:00', 'closed' => false],
                ]),
                'doctor_count' => 250,
                'average_rating' => 4.8,
                'rating_count' => 1800,
                'is_verified' => true,
                'is_featured' => true,
                'status' => 'active',
            ],

            // مراكز طبية في دبي
            [
                'name' => 'المركز الطبي الأمريكي دبي',
                'type' => 'medical_center',
                'email' => 'info@amcdubai.ae',
                'phone' => '+97143456789',
                'website' => 'https://www.amcdubai.ae',
                'address'=> 'دبي مارينا، دبي',
                'city' => 'دبي',
                'state' => 'إمارة دبي',
                'country' => 'الإمارات',
                'postal_code' => '00000',
                'latitude' => 25.0782,
                'longitude' => 55.1395,
                'description' => 'مركز طبي متكامل يقدم خدمات صحية عالية الجودة وفق المعايير الأمريكية.',
                'services' => json_encode(['استشارات متخصصة', 'فحوصات شاملة', 'تطعيمات', 'صحة المرأة', 'صحة الرجل', 'تغذية']),
                'facilities' => json_encode(['مواقف سيارات تحت الأرض', 'إنترنت فائق السرعة', 'غرف كشف فاخرة', 'كافيتيريا', 'صيدلية']),
                'insurance_providers' => json_encode(['أكسا الخليج', 'أسيج', 'بيانات', 'تكافل', 'ألفا']),
                'specialties' => json_encode($specialties->take(15)->pluck('id')->toArray()),
                'working_hours' => json_encode([
                    'sunday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                    'monday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                    'tuesday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                    'wednesday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                    'thursday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                    'friday' => ['open' => '09:00', 'close' => '18:00', 'closed' => false],
                    'saturday' => ['open' => '09:00', 'close' => '17:00', 'closed' => false],
                ]),
                'doctor_count' => 45,
                'average_rating' => 4.5,
                'rating_count' => 420,
                'is_verified' => true,
                'is_featured' => true,
                'status' => 'active',
            ],

            // عيادات في دبي
            [
                'name' => 'عيادة البرج الطبية',
                'type' => 'clinic',
                'email' => 'info@burjclinic.ae',
                'phone' => '+97143448899',
                'website' => 'https://www.burjclinic.ae',
                'address' => 'دبي مول، دبي',
                'city' => 'دبي',
                'state' => 'إمارة دبي',
                'country' => 'الإمارات',
                'postal_code' => '00000',
                'latitude' => 25.1972,
                'longitude' => 55.2794,
                'description' => 'عيادة فاخرة تقع في برج خليفة تقدم خدمات طبية متخصصة.',
                'services' => json_encode(['استشارات فاخرة', 'فحوصات وقائية', 'تجميل', 'جلدية', 'تغذية']),
                'facilities' => json_encode(['مواقف فندقية', 'إنترنت فائق', 'غرف فاخرة', 'مشروبات مجانية', 'خدمة التوصيل']),
                'insurance_providers' => json_encode(['أكسا الخليج', 'ألفا', 'بيانات']),
                'specialties' => json_encode($specialties->whereIn('name_en', ['Dermatology', 'Cosmetic Surgery', 'Nutrition'])->pluck('id')->toArray()),
                'working_hours' => json_encode([
                    'sunday' => ['open' => '10:00', 'close' => '20:00', 'closed' => false],
                    'monday' => ['open' => '10:00', 'close' => '20:00', 'closed' => false],
                    'tuesday' => ['open' => '10:00', 'close' => '20:00', 'closed' => false],
                    'wednesday' => ['open' => '10:00', 'close' => '20:00', 'closed' => false],
                    'thursday' => ['open' => '10:00', 'close' => '20:00', 'closed' => false],
                    'friday' => ['open' => '14:00', 'close' => '20:00', 'closed' => false],
                    'saturday' => ['open' => '10:00', 'close' => '18:00', 'closed' => false],
                ]),
                'doctor_count' => 15,
                'average_rating' => 4.3,
                'rating_count' => 210,
                'is_verified' => true,
                'is_featured' => true,
                'status' => 'active',
            ],

            // عيادات في الشارقة
            [
                'name' => 'عيادة الشارقة للأسنان',
                'type' => 'clinic',
                'email' => 'info@sharjahdental.ae',
                'phone' => '+97165333333',
                'website' => 'https://www.sharjahdental.ae',
                'address' => 'الشارقة',
                'city' => 'الشارقة',
                'state' => 'إمارة الشارقة',
                'country' => 'الإمارات',
                'postal_code' => '00000',
                'latitude' => 25.3463,
                'longitude' => 55.4209,
                'description' => 'عيادة متخصصة في طب الأسنان باستخدام أحدث التقنيات العالمية.',
                'services' => json_encode(['تبييض الأسنان', 'تقويم', 'زراعة', 'علاج عصب', 'تنظيف']),
                'facilities' => json_encode(['مواقف سيارات', 'إنترنت', 'تكييف', 'غرف علاج مريحة']),
                'insurance_providers' => json_encode(['أكسا الخليج', 'نورا', 'بيانات']),
                'specialties' => json_encode($specialties->where('name_en', 'like', '%Dental%')->pluck('id')->toArray()),
                'working_hours' => json_encode([
                    'sunday' => ['open' => '09:00', 'close' => '19:00', 'closed' => false],
                    'monday' => ['open' => '09:00', 'close' => '19:00', 'closed' => false],
                    'tuesday' => ['open' => '09:00', 'close' => '19:00', 'closed' => false],
                    'wednesday' => ['open' => '09:00', 'close' => '19:00', 'closed' => false],
                    'thursday' => ['open' => '09:00', 'close' => '19:00', 'closed' => false],
                    'friday' => ['open' => '16:00', 'close' => '20:00', 'closed' => false],
                    'saturday' => ['open' => '09:00', 'close' => '18:00', 'closed' => false],
                ]),
                'doctor_count' => 8,
                'average_rating' => 4.6,
                'rating_count' => 185,
                'is_verified' => true,
                'is_featured' => false,
                'status' => 'active',
            ],

            // مختبرات في دبي
            [
                'name' => 'مختبرات ميدلاب',
                'type' => 'lab',
                'email' => 'info@medlabs.ae',
                'phone' => '+97143449900',
                'website' => 'https://www.medlabs.ae',
                'address' => 'المركز التجاري، دبي',
                'city' => 'دبي',
                'state' => 'إمارة دبي',
                'country' => 'الإمارات',
                'postal_code' => '00000',
                'latitude' => 25.2048,
                'longitude' => 55.2708,
                'description' => 'مختبرات طبية معتمدة تقدم خدمات تحاليل دقيقة وسريعة.',
                'services' => json_encode(['تحاليل الدم', 'فحوصات كيميائية', 'تحاليل هرمونية', 'فحوصات وراثية']),
                'facilities' => json_encode(['مواقف سيارات', 'استقبال', 'غرف سحب عينات', 'نتائج إلكترونية']),
                'insurance_providers' => json_encode(['أكسا الخليج', 'بيانات', 'تكافل']),
                'specialties' => json_encode([]),
                'working_hours' => json_encode([
                    'sunday' => ['open' => '07:00', 'close' => '22:00', 'closed' => false],
                    'monday' => ['open' => '07:00', 'close' => '22:00', 'closed' => false],
                    'tuesday' => ['open' => '07:00', 'close' => '22:00', 'closed' => false],
                    'wednesday' => ['open' => '07:00', 'close' => '22:00', 'closed' => false],
                    'thursday' => ['open' => '07:00', 'close' => '22:00', 'closed' => false],
                    'friday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                    'saturday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                ]),
                'doctor_count' => 6,
                'average_rating' => 4.4,
                'rating_count' => 320,
                'is_verified' => true,
                'is_featured' => false,
                'status' => 'active',
            ],

            // صيدليات في دبي
            [
                'name' => 'صيدلية الحياة',
                'type' => 'pharmacy',
                'email' => 'info@life-pharmacy.ae',
                'phone' => '+97143441122',
                'website' => 'https://www.life-pharmacy.ae',
                'address' => 'مول الإمارات، دبي',
                'city' => 'دبي',
                'state' => 'إمارة دبي',
                'country' => 'الإمارات',
                'postal_code' => '00000',
                'latitude' => 25.1172,
                'longitude' => 55.2019,
                'description' => 'صيدلية 24 ساعة تقدم منتجات طبية وعناية شخصية.',
                'services' => json_encode(['أدوية موصوفة', 'مستحضرات تجميل', 'مستلزمات طبية', 'تغذية', 'عناية بالبشرة']),
                'facilities' => json_encode(['مواقف مول', 'خدمة 24 ساعة', 'توصيل مجاني', 'استشارة صيدلانية']),
                'insurance_providers' => json_encode([]),
                'specialties' => json_encode([]),
                'working_hours' => json_encode([
                    'sunday' => ['open' => '00:00', 'close' => '23:59', 'closed' => false],
                    'monday' => ['open' => '00:00', 'close' => '23:59', 'closed' => false],
                    'tuesday' => ['open' => '00:00', 'close' => '23:59', 'closed' => false],
                    'wednesday' => ['open' => '00:00', 'close' => '23:59', 'closed' => false],
                    'thursday' => ['open' => '00:00', 'close' => '23:59', 'closed' => false],
                    'friday' => ['open' => '00:00', 'close' => '23:59', 'closed' => false],
                    'saturday' => ['open' => '00:00', 'close' => '23:59', 'closed' => false],
                ]),
                'doctor_count' => 2,
                'average_rating' => 4.2,
                'rating_count' => 450,
                'is_verified' => true,
                'is_featured' => false,
                'status' => 'active',
            ],

            // مركز في عجمان
            [
                'name' => 'مركز عجمان الطبي',
                'type' => 'medical_center',
                'email' => 'info@ajmanmedical.ae',
                'phone' => '+97167445566',
                'website' => 'https://www.ajmanmedical.ae',
                'address' => 'عجمان',
                'city' => 'عجمان',
                'state' => 'إمارة عجمان',
                'country' => 'الإمارات',
                'postal_code' => '00000',
                'latitude' => 25.4052,
                'longitude' => 55.5136,
                'description' => 'مركز طبي متكامل في إمارة عجمان يقدم خدمات طبية متنوعة.',
                'services' => json_encode(['استشارات عامة', 'فحوصات', 'أشعة بسيطة', 'طوارئ', 'تحاليل']),
                'facilities' => json_encode(['مواقف سيارات', 'استقبال', 'غرف كشف', 'صيدلية']),
                'insurance_providers' => json_encode(['أكسا الخليج', 'نورا']),
                'specialties' => json_encode($specialties->take(8)->pluck('id')->toArray()),
                'working_hours' => json_encode([
                    'sunday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                    'monday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                    'tuesday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                    'wednesday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                    'thursday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                    'friday' => ['open' => '14:00', 'close' => '20:00', 'closed' => false],
                    'saturday' => ['open' => '08:00', 'close' => '18:00', 'closed' => false],
                ]),
                'doctor_count' => 25,
                'average_rating' => 4.1,
                'rating_count' => 280,
                'is_verified' => true,
                'is_featured' => false,
                'status' => 'active',
            ],

            // مركز في أم القيوين
            [
                'name' => 'مركز أم القيوين الصحي',
                'type' => 'medical_center',
                'email' => 'info@uaqhealth.ae',
                'phone' => '+97167667788',
                'website' => 'https://www.uaqhealth.ae',
                'address' => 'أم القيوين',
                'city' => 'أم القيوين',
                'state' => 'إمارة أم القيوين',
                'country' => 'الإمارات',
                'postal_code' => '00000',
                'latitude' => 25.5651,
                'longitude' => 55.5552,
                'description' => 'مركز صحي حكومي في أم القيوين يقدم خدمات الرعاية الصحية الأساسية.',
                'services' => json_encode(['استشارات عامة', 'تطعيمات', 'رعاية أمومة وطفولة', 'صحة مدرسية', 'طب أسرة']),
                'facilities' => json_encode(['مواقف سيارات', 'قاعة انتظار', 'غرف كشف', 'صيدلية صغيرة']),
                'insurance_providers' => json_encode(['حكومي']),
                'specialties' => json_encode($specialties->whereIn('name_en', ['Family Medicine', 'Pediatrics', 'Obstetrics'])->pluck('id')->toArray()),
                'working_hours' => json_encode([
                    'sunday' => ['open' => '07:30', 'close' => '15:30', 'closed' => false],
                    'monday' => ['open' => '07:30', 'close' => '15:30', 'closed' => false],
                    'tuesday' => ['open' => '07:30', 'close' => '15:30', 'closed' => false],
                    'wednesday' => ['open' => '07:30', 'close' => '15:30', 'closed' => false],
                    'thursday' => ['open' => '07:30', 'close' => '15:30', 'closed' => false],
                    'friday' => ['open' => 'closed', 'close' => 'closed', 'closed' => true],
                    'saturday' => ['open' => 'closed', 'close' => 'closed', 'closed' => true],
                ]),
                'doctor_count' => 12,
                'average_rating' => 4.0,
                'rating_count' => 150,
                'is_verified' => true,
                'is_featured' => false,
                'status' => 'active',
            ],

            // مركز في رأس الخيمة
            [
                'name' => 'مستشفى صقر الحكومي',
                'type' => 'hospital',
                'email' => 'info@saqrhospital.ae',
                'phone' => '+97172333333',
                'website' => 'https://www.saqrhospital.ae',
                'address' => 'رأس الخيمة',
                'city' => 'رأس الخيمة',
                'state' => 'إمارة رأس الخيمة',
                'country' => 'الإمارات',
                'postal_code' => '00000',
                'latitude' => 25.7915,
                'longitude' => 55.9468,
                'description' => 'مستشفى حكومي رئيسي في رأس الخيمة يقدم خدمات طبية متكاملة.',
                'services' => json_encode(['استشارات متخصصة', 'عمليات', 'طوارئ', 'أشعة', 'مختبرات', 'علاج طبيعي']),
                'facilities' => json_encode(['مواقف واسعة', 'صيدلية', 'مطعم', 'مصلى', 'حديقة', 'بنك']),
                'insurance_providers' => json_encode(['حكومي', 'أكسا الخليج', 'بيانات']),
                'specialties' => json_encode($specialties->take(12)->pluck('id')->toArray()),
                'working_hours' => json_encode([
                    'sunday' => ['open' => '08:00', 'close' => '22:00', 'closed' => false],
                    'monday' => ['open' => '08:00', 'close' => '22:00', 'closed' => false],
                    'tuesday' => ['open' => '08:00', 'close' => '22:00', 'closed' => false],
                    'wednesday' => ['open' => '08:00', 'close' => '22:00', 'closed' => false],
                    'thursday' => ['open' => '08:00', 'close' => '22:00', 'closed' => false],
                    'friday' => ['open' => '14:00', 'close' => '22:00', 'closed' => false],
                    'saturday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                ]),
                'doctor_count' => 95,
                'average_rating' => 4.3,
                'rating_count' => 620,
                'is_verified' => true,
                'is_featured' => false,
                'status' => 'active',
            ],

            // مركز في الفجيرة
            [
                'name' => 'مستشفى الفجيرة',
                'type' => 'hospital',
                'email' => 'info@fujairahhospital.ae',
                'phone' => '+97192224444',
                'website' => 'https://www.fujairahhospital.ae',
                'address' => 'الفجيرة',
                'city' => 'الفجيرة',
                'state' => 'إمارة الفجيرة',
                'country' => 'الإمارات',
                'postal_code' => '00000',
                'latitude' => 25.1288,
                'longitude' => 56.3265,
                'description' => 'المستشفى الرئيسي في إمارة الفجيرة يقدم خدمات طبية شاملة.',
                'services' => json_encode(['رعاية صحية متكاملة', 'طوارئ 24 ساعة', 'عمليات', 'أشعة', 'مختبرات']),
                'facilities' => json_encode(['مواقف سيارات', 'استقبال', 'صيدلية', 'كافيتيريا', 'مصلى']),
                'insurance_providers' => json_encode(['حكومي', 'أكسا الخليج']),
                'specialties' => json_encode($specialties->take(10)->pluck('id')->toArray()),
                'working_hours' => json_encode([
                    'sunday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                    'monday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                    'tuesday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                    'wednesday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                    'thursday' => ['open' => '08:00', 'close' => '20:00', 'closed' => false],
                    'friday' => ['open' => '14:00', 'close' => '20:00', 'closed' => false],
                    'saturday' => ['open' => '08:00', 'close' => '18:00', 'closed' => false],
                ]),
                'doctor_count' => 65,
                'average_rating' => 4.2,
                'rating_count' => 380,
                'is_verified' => true,
                'is_featured' => false,
                'status' => 'active',
            ],
        ];

        foreach ($medicalCenters as $centerData) {
            // إنشاء slug تلقائي
            $slug = Str::slug($centerData['name'], '-', 'ar');
            $originalSlug = $slug;
            $counter = 1;

            while (MedicalCenter::where('slug', $slug)->exists()) {
                $slug = $originalSlug . '-' . $counter;
                $counter++;
            }

            $centerData['slug'] = $slug;
            $centerData['created_at'] = Carbon::now();
            $centerData['updated_at'] = Carbon::now();

            MedicalCenter::create($centerData);
        }

        $this->command->info('تم إنشاء ' . count($medicalCenters) . ' مركز طبي في الإمارات بنجاح!');
    }
}