<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SpecialtiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // تعطيل قيود المفاتيح الخارجية للسماح بإدراج معرفات محددة أو تفريغ الجدول
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // DB::table('specialties')->truncate(); // اختياري: إذا كنت تريد مسح الجدول أولاً

        $specialties = [
            [
                'id' => 1,
                'name_ar' => 'طب الباطنة',
                'name_en' => 'Internal Medicine',
                'description_ar' => 'تشخيص وعلاج أمراض الأعضاء الداخلية للبالغين',
                'description_en' => 'Diagnosis and treatment of internal organ diseases in adults',
                'image' => 'specialties/specialty_1765043736_z4UGxEWSkq.webp',
                'icon' => 'specialties/icons/icon_1765043737_LBC43R7nrW.png',
                'color' => '#3498db',
                'is_active' => 1,
                'is_featured' => 1,
                'is_emergency_available' => 0,
                'order' => 1,
                'doctors_count' => 0,
                'consultations_count' => 0,
                'children_count' => 3,
                'average_consultation_fee' => 0.00,
                'min_consultation_fee' => 0.00,
                'max_consultation_fee' => 0.00,
                'average_rating' => 0.0,
                'total_reviews' => 0,
                'slug_ar' => 'tb-albatn',
                'slug_en' => 'internal-medicine',
                'meta_title_ar' => NULL,
                'meta_title_en' => NULL,
                'meta_description_ar' => NULL,
                'meta_description_en' => NULL,
                'keywords' => NULL,
                'parent_id' => NULL,
                'level' => 1,
                'requirements' => NULL,
                'skills' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-12-02 00:51:44',
                'updated_at' => '2025-12-06 09:55:37'
            ],
            [
                'id' => 2,
                'name_ar' => 'طب الأطفال',
                'name_en' => 'Pediatrics',
                'description_ar' => 'رعاية صحية للأطفال من الولادة حتى المراهقة',
                'description_en' => 'Healthcare for children from birth to adolescence',
                'image' => 'specialties/specialty_1765060886_uovuNdczjH.webp',
                'icon' => 'specialties/icons/icon_1765060886_4kI6dYo3de.svg',
                'color' => '#e74c3c',
                'is_active' => 1,
                'is_featured' => 1,
                'is_emergency_available' => 0,
                'order' => 2,
                'doctors_count' => 0,
                'consultations_count' => 0,
                'children_count' => 1,
                'average_consultation_fee' => 0.00,
                'min_consultation_fee' => 0.00,
                'max_consultation_fee' => 0.00,
                'average_rating' => 0.0,
                'total_reviews' => 0,
                'slug_ar' => 'tb-alatfal',
                'slug_en' => 'pediatrics',
                'meta_title_ar' => NULL,
                'meta_title_en' => NULL,
                'meta_description_ar' => NULL,
                'meta_description_en' => NULL,
                'keywords' => NULL,
                'parent_id' => NULL,
                'level' => 1,
                'requirements' => NULL,
                'skills' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-12-02 00:51:44',
                'updated_at' => '2025-12-06 14:41:26'
            ],
            [
                'id' => 3,
                'name_ar' => 'جراحة عامة',
                'name_en' => 'General Surgery',
                'description_ar' => 'إجراء العمليات الجراحية لمختلف أجزاء الجسم',
                'description_en' => 'Performing surgical procedures on various body parts',
                'image' => 'specialties/specialty_1765061193_HdflqagAdG.webp',
                'icon' => 'specialties/icons/icon_1765061193_LEiOpmLJDH.svg',
                'color' => '#2ecc71',
                'is_active' => 1,
                'is_featured' => 1,
                'is_emergency_available' => 0,
                'order' => 3,
                'doctors_count' => 0,
                'consultations_count' => 0,
                'children_count' => 1,
                'average_consultation_fee' => 0.00,
                'min_consultation_fee' => 0.00,
                'max_consultation_fee' => 0.00,
                'average_rating' => 0.0,
                'total_reviews' => 0,
                'slug_ar' => 'grah-aaam',
                'slug_en' => 'general-surgery',
                'meta_title_ar' => NULL,
                'meta_title_en' => NULL,
                'meta_description_ar' => NULL,
                'meta_description_en' => NULL,
                'keywords' => NULL,
                'parent_id' => NULL,
                'level' => 1,
                'requirements' => NULL,
                'skills' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-12-02 00:51:44',
                'updated_at' => '2025-12-06 14:46:33'
            ],
            [
                'id' => 4,
                'name_ar' => 'أمراض النساء والتوليد',
                'name_en' => 'Obstetrics and Gynecology',
                'description_ar' => 'رعاية صحة المرأة والحمل والولادة',
                'description_en' => 'Women\'s health care, pregnancy and childbirth',
                'image' => 'specialties/specialty_1765061236_gH9QN20F8d.webp',
                'icon' => 'specialties/icons/icon_1765061236_5ljdVUagLF.svg',
                'color' => '#9b59b6',
                'is_active' => 1,
                'is_featured' => 1,
                'is_emergency_available' => 0,
                'order' => 4,
                'doctors_count' => 0,
                'consultations_count' => 0,
                'children_count' => 0,
                'average_consultation_fee' => 0.00,
                'min_consultation_fee' => 0.00,
                'max_consultation_fee' => 0.00,
                'average_rating' => 0.0,
                'total_reviews' => 0,
                'slug_ar' => 'amrad-alnsaaa-oaltolyd',
                'slug_en' => 'obstetrics-and-gynecology',
                'meta_title_ar' => NULL,
                'meta_title_en' => NULL,
                'meta_description_ar' => NULL,
                'meta_description_en' => NULL,
                'keywords' => NULL,
                'parent_id' => NULL,
                'level' => 1,
                'requirements' => NULL,
                'skills' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-12-02 00:51:44',
                'updated_at' => '2025-12-06 14:47:16'
            ],
            [
                'id' => 5,
                'name_ar' => 'طب القلب',
                'name_en' => 'Cardiology',
                'description_ar' => 'تشخيص وعلاج أمراض القلب والأوعية الدموية',
                'description_en' => 'Diagnosis and treatment of heart and blood vessel diseases',
                'image' => 'specialties/specialty_1765061374_jUyac5vheG.webp',
                'icon' => 'specialties/icons/icon_1765061374_81PGoydM08.svg',
                'color' => '#e67e22',
                'is_active' => 1,
                'is_featured' => 1,
                'is_emergency_available' => 0,
                'order' => 5,
                'doctors_count' => 0,
                'consultations_count' => 0,
                'children_count' => 0,
                'average_consultation_fee' => 0.00,
                'min_consultation_fee' => 0.00,
                'max_consultation_fee' => 0.00,
                'average_rating' => 0.0,
                'total_reviews' => 0,
                'slug_ar' => 'tb-alklb',
                'slug_en' => 'cardiology',
                'meta_title_ar' => NULL,
                'meta_title_en' => NULL,
                'meta_description_ar' => NULL,
                'meta_description_en' => NULL,
                'keywords' => NULL,
                'parent_id' => NULL,
                'level' => 1,
                'requirements' => NULL,
                'skills' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-12-02 00:51:44',
                'updated_at' => '2025-12-06 14:49:34'
            ],
            [
                'id' => 6,
                'name_ar' => 'أمراض الجهاز الهضمي',
                'name_en' => 'Gastroenterology',
                'description_ar' => NULL,
                'description_en' => NULL,
                'image' => 'specialties/specialty_1765043811_okwrYlA94n.webp',
                'icon' => 'specialties/icons/icon_1765043811_7yKqGBWTuf.svg',
                'color' => '#EF4444',
                'is_active' => 1,
                'is_featured' => 0,
                'is_emergency_available' => 0,
                'order' => 1,
                'doctors_count' => 0,
                'consultations_count' => 0,
                'children_count' => 0,
                'average_consultation_fee' => 0.00,
                'min_consultation_fee' => 0.00,
                'max_consultation_fee' => 0.00,
                'average_rating' => 0.0,
                'total_reviews' => 0,
                'slug_ar' => 'amrad-alghaz-alhdmy',
                'slug_en' => 'gastroenterology',
                'meta_title_ar' => NULL,
                'meta_title_en' => NULL,
                'meta_description_ar' => NULL,
                'meta_description_en' => NULL,
                'keywords' => NULL,
                'parent_id' => 1,
                'level' => 2,
                'requirements' => NULL,
                'skills' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-12-02 00:51:44',
                'updated_at' => '2025-12-06 09:56:51'
            ],
            [
                'id' => 7,
                'name_ar' => 'أمراض الكلى',
                'name_en' => 'Nephrology',
                'description_ar' => NULL,
                'description_en' => NULL,
                'image' => 'specialties/specialty_1765061079_XFHUlkUXHQ.webp',
                'icon' => 'specialties/icons/icon_1765061079_GCvcVvIayS.png',
                'color' => '#EF4444',
                'is_active' => 1,
                'is_featured' => 0,
                'is_emergency_available' => 0,
                'order' => 2,
                'doctors_count' => 0,
                'consultations_count' => 0,
                'children_count' => 0,
                'average_consultation_fee' => 0.00,
                'min_consultation_fee' => 0.00,
                'max_consultation_fee' => 0.00,
                'average_rating' => 0.0,
                'total_reviews' => 0,
                'slug_ar' => 'amrad-alkl',
                'slug_en' => 'nephrology',
                'meta_title_ar' => NULL,
                'meta_title_en' => NULL,
                'meta_description_ar' => NULL,
                'meta_description_en' => NULL,
                'keywords' => NULL,
                'parent_id' => 1,
                'level' => 2,
                'requirements' => NULL,
                'skills' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-12-02 00:51:44',
                'updated_at' => '2025-12-06 14:44:39'
            ],
            [
                'id' => 8,
                'name_ar' => 'أمراض الروماتيزم',
                'name_en' => 'Rheumatology',
                'description_ar' => NULL,
                'description_en' => NULL,
                'image' => NULL,
                'icon' => NULL,
                'color' => '#10B981',
                'is_active' => 1,
                'is_featured' => 0,
                'is_emergency_available' => 0,
                'order' => 3,
                'doctors_count' => 0,
                'consultations_count' => 0,
                'children_count' => 0,
                'average_consultation_fee' => 0.00,
                'min_consultation_fee' => 0.00,
                'max_consultation_fee' => 0.00,
                'average_rating' => 0.0,
                'total_reviews' => 0,
                'slug_ar' => 'amrad-alromatyzm',
                'slug_en' => 'rheumatology',
                'meta_title_ar' => NULL,
                'meta_title_en' => NULL,
                'meta_description_ar' => NULL,
                'meta_description_en' => NULL,
                'keywords' => NULL,
                'parent_id' => 1,
                'level' => 2,
                'requirements' => NULL,
                'skills' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-12-02 00:51:44',
                'updated_at' => '2025-12-02 00:51:44'
            ],
            [
                'id' => 9,
                'name_ar' => 'جراحة الأطفال',
                'name_en' => 'Pediatric Surgery',
                'description_ar' => NULL,
                'description_en' => NULL,
                'image' => 'specialties/specialty_1765043895_1bYZeg25AH.webp',
                'icon' => 'specialties/icons/icon_1765043895_1cCGHHvTkQ.svg',
                'color' => '#10B981',
                'is_active' => 1,
                'is_featured' => 0,
                'is_emergency_available' => 0,
                'order' => 1,
                'doctors_count' => 0,
                'consultations_count' => 0,
                'children_count' => 0,
                'average_consultation_fee' => 0.00,
                'min_consultation_fee' => 0.00,
                'max_consultation_fee' => 0.00,
                'average_rating' => 0.0,
                'total_reviews' => 0,
                'slug_ar' => 'grah-alatfal',
                'slug_en' => 'pediatric-surgery',
                'meta_title_ar' => NULL,
                'meta_title_en' => NULL,
                'meta_description_ar' => NULL,
                'meta_description_en' => NULL,
                'keywords' => NULL,
                'parent_id' => 2,
                'level' => 2,
                'requirements' => NULL,
                'skills' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-12-02 00:51:44',
                'updated_at' => '2025-12-06 09:58:15'
            ],
            [
                'id' => 10,
                'name_ar' => 'جراحة القلب',
                'name_en' => 'Cardiac Surgery',
                'description_ar' => NULL,
                'description_en' => NULL,
                'image' => 'specialties/specialty_1765043936_A9FbTaLHWS.webp',
                'icon' => 'specialties/icons/icon_1765043936_pKL2HHH8nE.png',
                'color' => '#EF4444',
                'is_active' => 1,
                'is_featured' => 0,
                'is_emergency_available' => 0,
                'order' => 1,
                'doctors_count' => 0,
                'consultations_count' => 0,
                'children_count' => 0,
                'average_consultation_fee' => 0.00,
                'min_consultation_fee' => 0.00,
                'max_consultation_fee' => 0.00,
                'average_rating' => 0.0,
                'total_reviews' => 0,
                'slug_ar' => 'grah-alklb',
                'slug_en' => 'cardiac-surgery',
                'meta_title_ar' => NULL,
                'meta_title_en' => NULL,
                'meta_description_ar' => NULL,
                'meta_description_en' => NULL,
                'keywords' => NULL,
                'parent_id' => 3,
                'level' => 2,
                'requirements' => NULL,
                'skills' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-12-02 00:51:44',
                'updated_at' => '2025-12-06 09:58:56'
            ]
        ];

        foreach ($specialties as $specialty) {
            DB::table('specialties')->updateOrInsert(
                ['id' => $specialty['id']],
                $specialty
            );
        }

        // إعادة تفعيل قيود المفاتيح الخارجية
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
